
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package generadores;

import java_cup.runtime.Symbol;
import java.util.ArrayList;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\024\000\002\002\004\000\002\012\004\000\002\002" +
    "\004\000\002\003\004\000\002\003\004\000\002\003\004" +
    "\000\002\003\004\000\002\003\003\000\002\005\010\000" +
    "\002\013\002\000\002\006\007\000\002\010\005\000\002" +
    "\010\004\000\002\010\003\000\002\011\003\000\002\011" +
    "\003\000\002\007\004\000\002\004\007\000\002\004\003" +
    "\000\002\004\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\055\000\004\007\004\001\002\000\014\004\020\013" +
    "\017\014\015\021\011\022\007\001\002\000\004\002\006" +
    "\001\002\000\004\002\001\001\002\000\014\004\020\013" +
    "\017\014\015\021\011\022\007\001\002\000\010\004\ufffa" +
    "\010\ufffa\022\ufffa\001\002\000\004\006\052\001\002\000" +
    "\014\004\020\013\017\014\015\021\011\022\007\001\002" +
    "\000\010\004\042\010\040\022\041\001\002\000\014\004" +
    "\020\013\017\014\015\021\011\022\007\001\002\000\004" +
    "\014\036\001\002\000\004\002\000\001\002\000\014\004" +
    "\020\013\017\014\015\021\011\022\007\001\002\000\004" +
    "\011\021\001\002\000\012\005\027\015\023\016\025\017" +
    "\022\001\002\000\014\005\ufff3\012\ufff3\015\ufff3\016\ufff3" +
    "\017\ufff3\001\002\000\012\005\027\015\023\016\025\017" +
    "\022\001\002\000\014\005\ufff4\012\ufff4\015\ufff4\016\ufff4" +
    "\017\ufff4\001\002\000\012\005\027\015\023\016\025\017" +
    "\022\001\002\000\004\012\ufff8\001\002\000\014\005\ufff2" +
    "\012\ufff2\015\ufff2\016\ufff2\017\ufff2\001\002\000\004\012" +
    "\031\001\002\000\014\004\ufff7\013\ufff7\014\ufff7\021\ufff7" +
    "\022\ufff7\001\002\000\012\005\027\015\023\016\025\017" +
    "\022\001\002\000\014\005\ufff6\012\ufff6\015\ufff6\016\ufff6" +
    "\017\ufff6\001\002\000\014\005\ufff5\012\ufff5\015\ufff5\016" +
    "\ufff5\017\ufff5\001\002\000\010\004\ufffb\010\ufffb\022\ufffb" +
    "\001\002\000\010\004\ufff1\010\ufff1\022\ufff1\001\002\000" +
    "\010\004\ufffd\010\ufffd\022\ufffd\001\002\000\004\002\uffef" +
    "\001\002\000\010\004\042\010\040\022\041\001\002\000" +
    "\004\006\044\001\002\000\004\002\uffff\001\002\000\004" +
    "\017\045\001\002\000\004\012\046\001\002\000\010\004" +
    "\042\010\040\022\041\001\002\000\004\002\ufff0\001\002" +
    "\000\004\002\uffee\001\002\000\010\004\ufffe\010\ufffe\022" +
    "\ufffe\001\002\000\004\004\053\001\002\000\004\011\054" +
    "\001\002\000\004\020\055\001\002\000\004\012\056\001" +
    "\002\000\014\004\ufff9\013\ufff9\014\ufff9\021\ufff9\022\ufff9" +
    "\001\002\000\010\004\ufffc\010\ufffc\022\ufffc\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\055\000\004\012\004\001\001\000\014\002\015\003" +
    "\012\005\011\006\013\007\007\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\003\056\005\011\006\013\007" +
    "\007\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\003\050\005\011\006\013\007\007\001\001\000\004\004" +
    "\042\001\001\000\012\003\036\005\011\006\013\007\007" +
    "\001\001\000\002\001\001\000\002\001\001\000\012\003" +
    "\034\005\011\006\013\007\007\001\001\000\002\001\001" +
    "\000\006\010\025\011\023\001\001\000\002\001\001\000" +
    "\006\010\033\011\023\001\001\000\002\001\001\000\006" +
    "\010\031\011\023\001\001\000\004\013\027\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\010\032\011\023\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\004\047\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\004\046\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public ArrayList<String> er = new ArrayList<>();
    public ArrayList<String> id_er = new ArrayList<>();
    public ArrayList<String> conjuntos = new ArrayList<>();
    public ArrayList<String> id_conjuntos = new ArrayList<>(); 
    public ArrayList<String> entradas = new ArrayList<>();
    public ArrayList<String> id_entradas = new ArrayList<>();
    public ArrayList<String> auxiliar;
    public ArrayList<ArrayList<String>> alfabeto = new ArrayList<>();
    public ArrayList<String> alfabeto_individual = new ArrayList<>();

    public void syntax_error(Symbol s){
        System.out.println("Error R de sintaxis: "+ s.value +" Linea "+(s.left+1)+" columna "+(s.right+1) );
    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{ 
        System.out.println("Error NR de sintaxis: "+ s.value +" Linea "+(s.left+1)+" columna "+(s.right+1) );
    }

    public ArrayList<String> getER(){
        return er;
    }
    public ArrayList<String> get_Id_ER(){
        return id_er;
    }
    public ArrayList<String> getConjuntos(){
        return conjuntos;
    }
    public ArrayList<String> get_id_conjuntos(){
        return id_conjuntos;
    }
    public ArrayList<String> getEntradas(){
        return entradas;
    }
    public ArrayList<String> get_id_entradas(){
        return id_entradas;
    }    
    public ArrayList<ArrayList<String>> get_alfabeto(){
        return alfabeto;
    }   

    public void add_alfabeto_individual(String texto){
        if (texto.contains("{")){
            texto = texto.replaceAll("\\{","");
            texto = texto.replaceAll("\\}","");
        }   
        if (!alfabeto_individual.contains(texto)){
            alfabeto_individual.add(texto);
        }     
    }

    public void add_alfabeto(ArrayList<String> texto){
        auxiliar = new ArrayList<>();
        auxiliar = (ArrayList<String>)texto.clone();
        alfabeto.add(auxiliar);  
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {


    String conjunto="";
    String expresionR = "";
    public void add_er(String texto){
        er.add(texto);
    }
    public void add_id_er(String texto){
        id_er.add(texto);
    }
    public void add_conjunto(String texto){
        conjuntos.add(texto);
    }
    public void add_id_conjunto(String texto){
        id_conjuntos.add(texto);
    }
    public void add_entrada(String texto){
        entradas.add(texto);
    }
    public void add_id_entrada(String texto){
        id_entradas.add(texto);
    }


    /*
    public void determinar_repetido(String texto){
        boolean enConj = false;
        boolean may=false,min=false,dig=false,ascii=false;
        String copia = texto;
        copia = copia.replace("\"","");
        char c = copia.charAt(0);
        int primero,segundo;
        for (String s: conjuntos){
            if (s.contains("~")){
                primero = s.charAt(0);
                segundo = s.charAt(2);
                if (primero >64 && segundo<91){
                    may = true;
                }else if (primero>47 && segundo<58){
                    dig = true;
                }else if (primero>96 && segundo<123){
                    min = true;
                }else{
                    ascii = true;
                }

                if (c >64 && c<91 && may){
                    enConj = true;
                    return;
                }else if (c>47 && c<58 && dig){
                    enConj = true;
                    return;
                }else if (c>96 && c<123 && min){
                    enConj = true;
                    return;
                }else if (c>=primero && c<=segundo && ascii){
                    enConj = true;
                    return;
                }
                ascii = false;
                dig = false;
                may = false;
                min = false;


            }else{
                copia = s;
                copia = copia.replaceAll(",","");
                if (copia.contains(Character.toString(c))){
                    return;
                }
            }
        }

        if (!enConj){
            add_alfabeto(texto);
        }
    }
    */


  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= SIGNO_APERTURA sentencias 
            {
              Object RESULT =null;
		

                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("inicio",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // sentencias ::= asignaciones cadenas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencias",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // asignaciones ::= asignacion asignaciones 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("asignaciones",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // asignaciones ::= expresiones asignaciones 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("asignaciones",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // asignaciones ::= COM_LINEA asignaciones 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("asignaciones",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // asignaciones ::= COMENTARIO asignaciones 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("asignaciones",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // asignaciones ::= seccion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("asignaciones",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // asignacion ::= CONJ DOSPUNTOS IDENTIFICADOR SIGNO_ASIGNACION NOTACION PUNTOCOMA 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int noleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int noright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String no = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                add_conjunto(no);
                add_id_conjunto(id);
                //add_alfabeto(no);
                //determinar_repetido(no);
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("asignacion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // NT$0 ::= 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;

                add_id_er(id);
                add_er(expresionR);
                expresionR="";
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // expresiones ::= IDENTIFICADOR SIGNO_ASIGNACION operacion NT$0 PUNTOCOMA 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		
                add_alfabeto(alfabeto_individual);
                alfabeto_individual.clear();
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresiones",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // operacion ::= SIGNO_COMB operacion operacion 
            {
              Object RESULT =null;
		int combleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int combright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String comb = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		
                expresionR += comb;
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("operacion",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // operacion ::= SIGNO_UNI operacion 
            {
              Object RESULT =null;
		int unileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int uniright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String uni = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                expresionR += uni;
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("operacion",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // operacion ::= sentencia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operacion",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // sentencia ::= TEXTO 
            {
              Object RESULT =null;
		int txtleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int txtright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String txt = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                expresionR += txt;
                add_alfabeto_individual(txt);
                //determinar_repetido(txt);
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // sentencia ::= CONJUNTO 
            {
              Object RESULT =null;
		int cnjleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cnjright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String cnj = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                add_alfabeto_individual(cnj);
                expresionR += cnj;
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // seccion ::= SEPARACION SEPARACION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccion",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // cadenas ::= IDENTIFICADOR DOSPUNTOS TEXTO PUNTOCOMA cadenas 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int txtleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int txtright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String txt = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		
                add_id_entrada(id);
                add_entrada(txt);
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cadenas",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // cadenas ::= SIGNO_CIERRE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cadenas",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // cadenas ::= COM_LINEA cadenas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cadenas",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
