
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package generadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEPARACION = 10;
  public static final int DOSPUNTOS = 4;
  public static final int SIGNO_UNI = 11;
  public static final int CONJUNTO = 3;
  public static final int SIGNO_COMB = 12;
  public static final int COMILLA_DOBLE = 19;
  public static final int EOF = 0;
  public static final int SIGNO_ASIGNACION = 7;
  public static final int COMILLA = 18;
  public static final int CONJ = 15;
  public static final int TEXTO = 13;
  public static final int error = 1;
  public static final int NOTACION = 14;
  public static final int SIGNO_CIERRE = 6;
  public static final int IDENTIFICADOR = 2;
  public static final int PUNTOCOMA = 8;
  public static final int COM_LINEA = 16;
  public static final int SALTO = 17;
  public static final int COMENTARIO = 9;
  public static final int SIGNO_APERTURA = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFICADOR",
  "CONJUNTO",
  "DOSPUNTOS",
  "SIGNO_APERTURA",
  "SIGNO_CIERRE",
  "SIGNO_ASIGNACION",
  "PUNTOCOMA",
  "COMENTARIO",
  "SEPARACION",
  "SIGNO_UNI",
  "SIGNO_COMB",
  "TEXTO",
  "NOTACION",
  "CONJ",
  "COM_LINEA",
  "SALTO",
  "COMILLA",
  "COMILLA_DOBLE"
  };
}

